# -*- coding: utf-8 -*-
"""R1.3: etiquetas cortas (`short`, máx. 22 caracteres) para los elementos cuya etiqueta de la línea de tiempo era larga.
Formato: id: (EN, ES). Los diseñadores llevan un solo `short` (su nombre no se traduce): se usa el primero. Las usa r1_limpieza.py; no cambia ningún otro texto."""
SHORTS = {
 # diseñadores
 'percier-fontaine': ('Percier & Fontaine', 'Percier y Fontaine'),
 'karl-friedrich-schinkel': ('Schinkel', 'Schinkel'),
 'pugin': ('Pugin', 'Pugin'),
 'capability-brown': ('Capability Brown', 'Capability Brown'),
 'soufflot': ('Soufflot', 'Soufflot'),
 'isambard-kingdom-brunel': ('Brunel', 'Brunel'),
 'thayaht': ('Thayaht', 'Thayaht'),
 'filippo-marinetti': ('Marinetti', 'Marinetti'),
 'stenberg-brothers': ('Stenberg', 'Stenberg'),
 'equipo-campana-del-no': ('NO campaign', 'NO campaign'),
 'hermanos-campana': ('Campana', 'Campana'),
 'duany-plater-zyberk': ('Duany & Plater-Zyberk', 'Duany y Plater-Zyberk'),
 'sanaa': ('SANAA', 'SANAA'),
 'pezo-von-ellrichshausen': ('Pezo–Ellrichshausen', 'Pezo–Ellrichshausen'),
 'lacaton-vassal': ('Lacaton & Vassal', 'Lacaton y Vassal'),
 'diller-scofidio-renfro': ('DS+R', 'DS+R'),
 'castiglioni': ('Castiglioni', 'Castiglioni'),
 'kinneir-calvert': ('Kinneir & Calvert', 'Kinneir y Calvert'),
 'bresciani-valdes-castillo-huidobro': ('Bresciani et al.', 'Bresciani et al.'),
 'vilanova-artigas': ('Vilanova Artigas', 'Vilanova Artigas'),
 'alberto-cruz-covarrubias': ('Alberto Cruz', 'Alberto Cruz'),
 'som': ('SOM', 'SOM'),
 'smithsons': ('Smithsons', 'Smithsons'),
 'pininfarina': ('Pinin Farina', 'Pinin Farina'),
 'charles-rennie-mackintosh': ('Mackintosh', 'Mackintosh'),
 'toulouse-lautrec': ('Toulouse-Lautrec', 'Toulouse-Lautrec'),
 'charles-frederick-worth': ('Worth', 'Worth'),
 'haussmann': ('Haussmann', 'Haussmann'),
 'william-le-baron-jenney': ('Jenney', 'Jenney'),
 'domenech-i-montaner': ('Domènech i Montaner', 'Domènech i Montaner'),
 'beggarstaffs': ('Beggarstaffs', 'Beggarstaffs'),
 'theophile-steinlen': ('Steinlen', 'Steinlen'),
 # obras
 'baskerville-virgil-1757': ('Baskerville’s Virgil', 'Virgilio Baskerville'),
 'bodoni-manuale-1788': ('Bodoni’s Manuale', 'Manuale de Bodoni'),
 'caslon-egyptian-1816': ('Caslon’s Egyptian', 'Egyptian de Caslon'),
 'bewick-quadrupeds-1790': ('Bewick’s Quadrupeds', 'Cuadrúpedos de Bewick'),
 'encyclopedie-plates-1762': ('Encyclopédie plates', 'Láminas Encyclopédie'),
 'commercial-political-atlas-1786': ('Playfair’s Atlas', 'Atlas de Playfair'),
 'blake-songs-1794': ('Blake’s Songs', 'Cantos de Blake'),
 'senefelder-lehrbuch-1818': ('Senefelder’s Course', 'Curso Senefelder'),
 'hokusai-great-wave-1831': ('The Great Wave', 'La gran ola'),
 'illustrated-london-news-1842': ('Ill. London News', 'Ill. London News'),
 'chippendale-ribbon-chair-1754': ('Ribbon-back chair', 'Silla de cintas'),
 'shaker-ladderback-chair-1800': ('Shaker chair', 'Silla shaker'),
 'boulton-ormolu-vases-1770': ('Boulton ormolu vases', 'Jarrones de Boulton'),
 'watt-rotative-engine-1781': ('Watt rotative engine', 'Máquina rotativa Watt'),
 'willow-pattern-1790': ('Willow pattern', 'Patrón Willow'),
 'rocket-locomotive-1829': ('Stephenson’s Rocket', 'Rocket de Stephenson'),
 'empire-silhouette-1800': ('Empire dress', 'Vestido Imperio'),
 'heideloff-gallery-of-fashion-1794': ('Gallery of Fashion', 'Gallery of Fashion'),
 'ackermann-fashion-plates-1809': ('Ackermann plates', 'Láminas Ackermann'),
 'marie-antoinette-gowns-1775': ('Bertin’s court gowns', 'Vestidos de Bertin'),
 'toile-de-jouy-1783': ('Toile de Jouy', 'Tela de Jouy'),
 'brummell-tailoring-1810': ('Brummell’s coat', 'Frac de Brummell'),
 'ironbridge-1779': ('Iron Bridge', 'Puente de hierro'),
 'osterley-etruscan-room-1775': ('Osterley Etruscan Room', 'Sala etrusca Osterley'),
 'malmaison-1800': ('Malmaison interiors', 'Interiores Malmaison'),
 'blenheim-park-1764': ('Blenheim Park', 'Parque de Blenheim'),
 'saline-royale-1779': ('Royal Saltworks', 'Salinas reales'),
 'cenotaph-newton-1784': ('Cenotaph for Newton', 'Cenotafio de Newton'),
 'la-moneda-1805': ('La Moneda', 'La Moneda'),
 'soane-museum-1812': ('Soane Museum', 'Museo Soane'),
 'royal-pavilion-1823': ('Royal Pavilion', 'Pabellón Real'),
 'university-of-virginia-1826': ('Univ. of Virginia', 'Univ. de Virginia'),
 'bibliotheque-sainte-genevieve-1850': ('Sainte-Geneviève', 'Sainte-Geneviève'),
 'bauhaus-exhibition-poster-1923': ('Bauhaus 1923 poster', 'Cartel Bauhaus 1923'),
 'intransigeant-poster-1925': ('L’Intransigeant poster', 'Cartel Intransigeant'),
 'man-with-movie-camera-poster-1929': ('Movie Camera poster', 'Cartel Hombre-cámara'),
 'dlia-golosa-1923': ('Dlia golosa', 'Dlia golosa'),
 'matter-swiss-posters-1935': ('Swiss tourism posters', 'Carteles de Suiza'),
 'lustig-new-directions-1941': ('New Directions jackets', 'Sobrecubiertas ND'),
 'ruhlmann-hotel-du-collectionneur-1925': ('Ruhlmann furniture', 'Mobiliario Ruhlmann'),
 'rodchenko-workers-club-1925': ('Workers’ Club', 'Club obrero'),
 'clarice-cliff-bizarre-1927': ('Bizarre ware', 'Vajilla Bizarre'),
 'lc2-armchair-1928': ('LC2 armchair', 'Sillón LC2'),
 'gg1-locomotive-1935': ('GG1 locomotive', 'Locomotora GG1'),
 'volksempfanger-1933': ('Volksempfänger', 'Volksempfänger'),
 'trench-coat-1914': ('Trench coat', 'Trench coat'),
 'chanel-jersey-1916': ('Chanel jersey', 'Jersey de Chanel'),
 'patou-lenglen-1921': ('Lenglen’s Patou outfit', 'Atuendo Lenglen-Patou'),
 'prozodezhda-1922': ('Prozodezhda', 'Prozodezhda'),
 'schott-perfecto-1928': ('Schott Perfecto', 'Schott Perfecto'),
 'kahlo-tehuana-1930': ('Kahlo’s Tehuana dress', 'Traje tehuana de Kahlo'),
 'letty-lynton-dress-1932': ('Letty Lynton dress', 'Vestido Letty Lynton'),
 'miranda-baiana-1939': ('Miranda’s baiana', 'Baiana de Miranda'),
 'mccardell-popover-1942': ('McCardell Popover', 'Popover de McCardell'),
 'glass-pavilion-1914': ('Glass Pavilion', 'Pabellón de Cristal'),
 'tatlin-tower-1920': ('Tatlin’s Tower', 'Torre de Tatlin'),
 'einstein-tower-1921': ('Einstein Tower', 'Torre Einstein'),
 'fallingwater-1937': ('Fallingwater', 'Fallingwater'),
 'dom-ino-1914': ('Dom-ino House', 'Casa Dom-ino'),
 'lovell-health-house-1929': ('Lovell Health House', 'Casa Lovell'),
 'bell-centennial-1978': ('Bell Centennial', 'Bell Centennial'),
 'nasa-worm-logo-1975': ('NASA worm logo', 'Logo gusano NASA'),
 'apple-rainbow-logo-1977': ('Apple rainbow logo', 'Logo arcoíris Apple'),
 'god-save-the-queen-1977': ('God Save the Queen', 'God Save the Queen'),
 'weingart-posters-1977': ('Weingart posters', 'Carteles de Weingart'),
 'unknown-pleasures-1979': ('Unknown Pleasures', 'Unknown Pleasures'),
 'cranbrook-new-discourse-1989': ('Cranbrook poster', 'Cartel Cranbrook'),
 'benetton-toscani-1989': ('Benetton campaigns', 'Campañas Benetton'),
 'information-landscapes-1994': ('Info. Landscapes', 'Paisajes de info.'),
 'cdc-sars-cov-2-illustration-2020': ('CDC SARS-CoV-2 image', 'Imagen CDC SARS-CoV-2'),
 'cosmopolitan-ai-cover-2022': ('Cosmopolitan AI', 'Cosmopolitan IA'),
 'braun-et66-1987': ('Braun ET 66', 'Braun ET 66'),
 'how-high-the-moon-1986': ('How High the Moon', 'How High the Moon'),
 'muji-cd-player-1999': ('Muji CD player', 'Reproductor CD Muji'),
 'armani-american-gigolo-1980': ('Armani jacket', 'Chaqueta Armani'),
 'van-herpen-crystallization-2010': ('Crystallization', 'Crystallization'),
 'lagerfeld-chanel-1983': ('Lagerfeld at Chanel', 'Lagerfeld en Chanel'),
 'grunge-perry-ellis-1992': ('Perry Ellis grunge', 'Grunge Perry Ellis'),
 'body-meets-dress-1997': ('Body Meets Dress', 'Body Meets Dress'),
 'helmut-lang-1998': ('Helmut Lang', 'Helmut Lang'),
 'piazza-d-italia-1978': ('Piazza d’Italia', 'Plaza de Italia'),
 'teatro-del-mondo-1979': ('Teatro del Mondo', 'Teatro del Mondo'),
 'strada-novissima-1980': ('Strada Novissima', 'Strada Novissima'),
 'staatsgalerie-stuttgart-1984': ('Staatsgalerie', 'Staatsgalerie'),
 'att-building-1984': ('AT&T Building', 'Edificio AT&T'),
 'hsbc-hong-kong-1986': ('HSBC Hong Kong', 'HSBC Hong Kong'),
 'lloyds-building-1986': ('Lloyd’s Building', 'Edificio Lloyd’s'),
 'museo-romano-merida-1986': ('Roman Art Museum', 'Museo Arte Romano'),
 'institut-monde-arabe-1987': ('Inst. Monde Arabe', 'Inst. Mundo Árabe'),
 'church-of-the-light-1989': ('Church of the Light', 'Iglesia de la Luz'),
 'barcelona-olympic-village-1992': ('Olympic Village', 'Villa Olímpica'),
 'kansai-airport-1994': ('Kansai Airport', 'Aeropuerto de Kansai'),
 'paper-church-kobe-1995': ('Paper Church', 'Iglesia de papel'),
 'petronas-towers-1996': ('Petronas Towers', 'Torres Petronas'),
 'reichstag-dome-1999': ('Reichstag Dome', 'Cúpula Reichstag'),
 'serralves-museum-1999': ('Serralves Museum', 'Museo de Serralves'),
 'gando-school-2001': ('Gando School', 'Escuela de Gando'),
 'kanazawa-museum-2004': ('Kanazawa Museum', 'Museo de Kanazawa'),
 'holocaust-memorial-berlin-2005': ('Holocaust Memorial', 'Memorial Holocausto'),
 'parque-biblioteca-espana-2007': ('Parque Biblioteca', 'Parque Biblioteca'),
 'birds-nest-2008': ('Bird’s Nest', 'Nido de Pájaro'),
 'ningbo-history-museum-2008': ('Ningbo Museum', 'Museo de Ningbo'),
 'museo-memoria-santiago-2010': ('Museum of Memory', 'Museo de la Memoria'),
 'tour-bois-le-pretre-2011': ('Bois-le-Prêtre', 'Bois-le-Prêtre'),
 'cctv-headquarters-2012': ('CCTV Headquarters', 'Sede de CCTV'),
 'heydar-aliyev-center-2012': ('Heydar Aliyev Center', 'Centro Heydar Aliyev'),
 'cardboard-cathedral-2013': ('Cardboard Cathedral', 'Catedral de cartón'),
 'sainsbury-wing-1991': ('Sainsbury Wing', 'Ala Sainsbury'),
 'elbphilharmonie-2017': ('Elbphilharmonie', 'Elbphilharmonie'),
 'man-golden-arm-1955': ('Golden Arm titles', 'Títulos Brazo de oro'),
 'sgt-pepper-cover-1967': ('Sgt. Pepper cover', 'Carátula Sgt. Pepper'),
 'dot-symbol-signs-1974': ('DOT symbols', 'Símbolos DOT'),
 'festival-britain-emblem-1951': ('Festival of Britain', 'Festival Britania'),
 'fillmore-posters-1966': ('Psychedelic posters', 'Carteles psicodélicos'),
 'black-panther-graphics-1967': ('Black Panther graphics', 'Gráfica Black Panther'),
 'avant-garde-lubalin-1968': ('Avant Garde', 'Avant Garde'),
 'tupperware-1946': ('Tupperware Wonderlier', 'Tupperware Wonderlier'),
 'noguchi-table-1947': ('Noguchi table', 'Mesa de Noguchi'),
 'juhl-chieftain-1949': ('Chieftain chair', 'Sillón Chieftain'),
 'butaque-chair-1950': ('Butaque chair', 'Butaque'),
 'bertoia-diamond-1952': ('Bertoia Diamond', 'Diamond de Bertoia'),
 'cadillac-eldorado-1959': ('Cadillac Eldorado', 'Cadillac Eldorado'),
 'ibm-selectric-1961': ('IBM Selectric', 'IBM Selectric'),
 'polypropylene-chair-1963': ('Polypropylene chair', 'Silla polipropileno'),
 'componibili-1967': ('Componibili', 'Componibili'),
 'vw-golf-1974': ('VW Golf Mk1', 'VW Golf Mk1'),
 'braun-t3-1958': ('Braun T3', 'Braun T3'),
 'engelbart-demo-1968': ('NLS and the mouse', 'NLS y el ratón'),
 'girard-herman-miller-textiles-1952': ('Girard textiles', 'Textiles de Girard'),
 'givenchy-breakfast-1961': ('Givenchy dress', 'Vestido Givenchy'),
 'zuzu-angel-collection-1971': ('Zuzu Angel collection', 'Colección Zuzu Angel'),
 'dvf-wrap-dress-1974': ('DVF wrap dress', 'Vestido cruzado DVF'),
 'pucci-prints-1951': ('Pucci printed silks', 'Sedas de Pucci'),
 'rabanne-12-dresses-1966': ('Rabanne’s 12 dresses', '12 vestidos Rabanne'),
 'casa-barragan-1948': ('Casa Barragán', 'Casa Barragán'),
 'chandigarh-1951': ('Chandigarh Capitol', 'Capital Chandigarh'),
 'guggenheim-new-york-1959': ('Guggenheim New York', 'Guggenheim Nueva York'),
 'yoyogi-gymnasium-1964': ('Yoyogi Gymnasium', 'Gimnasio Yoyogi'),
 'tlatelolco-1964': ('Tlatelolco', 'Tlatelolco'),
 'aterro-flamengo-1965': ('Parque do Flamengo', 'Parque do Flamengo'),
 'unidad-vecinal-portales-1966': ('U. V. Portales', 'U. V. Portales'),
 'banco-de-londres-1966': ('Banco de Londres', 'Banco de Londres'),
 'ciudad-abierta-1970': ('Ciudad Abierta', 'Ciudad Abierta'),
 'munich-olympic-park-1972': ('Munich Olympic Park', 'Parque Olímpico Múnich'),
 'curitiba-rit-1974': ('Curitiba transport', 'Transporte Curitiba'),
 'jatiya-sangsad-dhaka-1982': ('Jatiya Sangsad', 'Parlamento de Dacca'),
 'glass-house-1949': ('Glass House', 'Casa de Vidrio'),
 'caracas-ciudad-universitaria-1953': ('Ciudad Universitaria', 'Ciudad Universitaria'),
 'los-manantiales-1958': ('Los Manantiales', 'Los Manantiales'),
 'atlantida-church-1960': ('Atlántida church', 'Iglesia de Atlántida'),
 'previ-lima-1969': ('PREVI Lima', 'PREVI Lima'),
 'alice-tenniel-1865': ('Tenniel’s Alice', 'Alicia de Tenniel'),
 'minard-napoleon-map-1869': ('Minard’s map', 'Mapa de Minard'),
 'priester-matches-1905': ('Priester poster', 'Cartel Priester'),
 'bradley-chap-book-1894': ('The Chap-Book', 'The Chap-Book'),
 'hohlwein-posters-1908': ('Hohlwein posters', 'Carteles de Hohlwein'),
 'edison-bulb-1879': ('Edison lamp', 'Lámpara de Edison'),
 'gillette-safety-razor-1903': ('Gillette razor', 'Afeitadora Gillette'),
 'stickley-craftsman-1901': ('Craftsman furniture', 'Muebles Craftsman'),
 'liberty-artistic-dress': ('Liberty dress', 'Vestido Liberty'),
 'crinoline-cage-1856': ('Cage crinoline', 'Crinolina de aros'),
 'vuitton-flat-trunk-1858': ('Vuitton flat trunk', 'Baúl plano Vuitton'),
 'jaeger-woollen-system-1884': ('Jaeger system', 'Sistema Jaeger'),
 'paris-metro-entrances': ('Paris Métro entrances', 'Entradas Métro París'),
 'haussmann-paris-1853': ('Haussmann’s Paris', 'París de Haussmann'),
 'central-park-1858': ('Central Park', 'Central Park'),
 'eixample-barcelona-1859': ('Eixample', 'Ensanche de Barcelona'),
 'opera-garnier-1875': ('Palais Garnier', 'Ópera Garnier'),
 'sagrada-familia-1882': ('Sagrada Família', 'Sagrada Família'),
 'home-insurance-building-1885': ('Home Insurance Bldg.', 'Home Insurance Bldg.'),
 'letchworth-1903': ('Letchworth', 'Letchworth'),
 'hill-house-1904': ('Hill House', 'Hill House'),
 'postsparkasse-1906': ('Postsparkasse', 'Postsparkasse'),
 'palau-musica-catalana-1908': ('Palau de la Música', 'Palau de la Música'),
 'museo-bellas-artes-santiago-1910': ('Museo Bellas Artes', 'Museo Bellas Artes'),
 'voysey-orchard-1899': ('The Orchard', 'The Orchard'),
 'ernst-ludwig-house-1901': ('Ernst Ludwig House', 'Casa Ernst Ludwig'),
}
