import subprocess, time, os, json
from playwright.sync_api import sync_playwright
import os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # the lhd folder
OUT = os.path.join(os.environ.get('LHD_SHOTS', '/tmp'), 'lhd-shots'); os.makedirs(OUT, exist_ok=True)
EXE = os.environ.get('CHROMIUM', '/opt/pw-browsers/chromium')
srv = subprocess.Popen(['php', '-S', '127.0.0.1:8765', '-t', ROOT], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(0.8)
ok = True
def check(cond, msg):
    global ok
    print(('PASS ' if cond else 'FAIL ') + msg)
    ok = ok and cond
try:
    with sync_playwright() as p:
        b = p.chromium.launch(executable_path=EXE)
        ctx = b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
        pg = ctx.new_page()
        errs = []
        pg.on('pageerror', lambda e: errs.append('PAGEERROR: ' + str(e)))
        for pat in ('**/fonts.googleapis.com/**', '**/fonts.gstatic.com/**'): pg.route(pat, lambda r: r.abort())
        pg.route('**/en.wikipedia.org/**', lambda r: r.fulfill(status=200, content_type='application/json', body='{"query":{"pages":{}}}'))
        pg.add_init_script("try{localStorage.setItem('lhd-lang','es')}catch(e){}")
        CL = os.environ.get('LHD_CLAVE', 'uai2026')
        pg.goto('http://127.0.0.1:8765/index.html?editar#frankfurt-kitchen'); pg.wait_for_timeout(800)
        check(pg.locator('#edPass').count() == 0 and pg.locator('#edModal').count() == 0, 'opening ?editar asks for no password')
        check(pg.locator('.p-edit').count() == 1 and pg.locator('#rvObs').count() == 1, 'pencil and Observaciones visible before the password')
        pg.click('.p-edit'); pg.wait_for_timeout(300)
        check(pg.locator('#edModal #edPass').count() == 1, 'first editing action asks for the password')
        pg.fill('#edPass', 'mala'); pg.press('#edPass', 'Enter'); pg.wait_for_timeout(1500)
        check(pg.locator('#edModalErr').inner_text().strip() != '' and pg.locator('#edModal').count() == 1, 'wrong password shows an error')
        pg.press('#edPass', 'Escape'); pg.wait_for_timeout(200)
        check(pg.locator('#edModal').count() == 0 and pg.locator('#edImgUrl').count() == 0, 'Esc cancels the dialog')
        pg.click('.p-edit'); pg.fill('#edPass', CL); pg.press('#edPass', 'Enter'); pg.wait_for_timeout(900)
        check(pg.locator('#edModal').count() == 0 and pg.locator('#edImgUrl').count() == 1, 'right password: the pencil action continues by itself')
        pg.fill('#edImgUrl', 'https://upload.wikimedia.org/wikipedia/commons/x/xx/Test.jpg'); pg.click('[data-edimgsave]'); pg.wait_for_timeout(500)
        check('Test.jpg' in (pg.locator('.p-img img').get_attribute('src') or ''), 'image override applied')
        check(pg.locator('.review[data-rv]').count() == 1 and pg.locator('.p-edit').count() == 1, 'Observaciones section and image pencil')
        check(pg.locator('.review h3').inner_text().strip().lower() == 'observaciones', 'section is called Observaciones')
        check(pg.locator('#rvChk').count() == 0 and pg.locator('.rv-badge').count() == 0, 'no Revisada checkbox nor badge')
        check(pg.locator('#panel details.sources').count() == 1, 'Fuentes section present in edit mode')
        check(pg.evaluate("() => { const p = document.querySelector('#panel'); const k = [...p.children]; const i = k.findIndex(e => e.matches('details.sources')); const r = k.findIndex(e => e.matches('.review')); return i === k.length - 1 && r === i - 1; }"), 'Observaciones right before Fuentes, Fuentes last')
        pg.fill('#rvObs', 'Revisar la fecha de instalación en Römerstadt.'); pg.click('[data-rvsave]'); pg.wait_for_timeout(500)
        check(pg.locator('#content .obs').count() >= 1, 'observed mark on the line')
        pg.screenshot(path=f'{OUT}/ed1.png')
        pg.click('#reviewBtn'); pg.wait_for_timeout(400)
        txt = pg.locator('#panel').inner_text().lower()
        check('revisión por ia' in txt and pg.locator('details.rv-det').count() == 3, 'summary: AI review plus three collapsible lists (fuentes, imágenes, observaciones)')
        check(pg.locator('details.rv-det[open]').count() == 0, 'the three lists open closed')
        check(pg.locator('.rv-tbl').count() == 4 and pg.locator('.rv-total').count() == 2, 'AI review and images: totals, by type and by era')
        for k in ('src', 'img', 'obs'): pg.click(f'details[data-rvd="{k}"] > summary'); pg.wait_for_timeout(150)
        check(pg.locator('details.rv-det[open]').count() == 3, 'the lists open and close')
        check('con imagen' in pg.locator('#panel').inner_text().lower() and pg.locator('details[data-rvd="img"] .rv-tbl').count() == 2, 'image figures by type and by era')
        check(all(x in pg.locator('details[data-rvd="img"]').inner_text() for x in ('Libre', 'Derechos reservados', 'Sucedánea', 'Sin imagen')), 'image filters present')
        pg.click('details[data-rvd="img"] [data-rvf="img:free"]'); pg.wait_for_timeout(200)
        check(pg.locator('details[data-rvd="img"][open]').count() == 1 and pg.locator('details[data-rvd="img"] .rv-row').count() > 5, 'image filter keeps the list open and lists cards')
        eras = pg.locator('details[data-rvd="src"] .chips').nth(1).inner_text()
        check('1914–1944' in eras and '1975–hoy' in eras and 'Modernismo' not in eras and 'Posguerra' not in eras, 'eras are named by years in the summary')
        check(pg.locator('#panel .rv-row[data-go="frankfurt-kitchen"]').count() >= 1, 'card listed under pending notes')
        check(pg.locator('details[data-rvd="img"] .rv-row.img img.rv-th').count() >= 1, 'images listed with thumbnail')
        pg.click('details[data-rvd="src"] [data-rvf="src:has"]'); pg.wait_for_timeout(200)
        check(pg.locator('details[data-rvd="src"] .rv-list .rv-row').count() > 0, 'chip "Con fuentes" lists cards')
        pg.screenshot(path=f'{OUT}/ed2.png')
        with pg.expect_download() as dl:
            pg.click('section [data-rvexport]')
        md = open(dl.value.path(), encoding='utf-8').read()
        check('1914–1944' in md and 'Imágenes cambiadas' in md and 'Fichas sin fuentes' in md and 'Römerstadt' in md, 'export has notes, changed images and the count without sources')
        pg.click('.rv-row[data-go="frankfurt-kitchen"]'); pg.wait_for_timeout(400)
        pg.click('[data-rvresolve]'); pg.wait_for_timeout(500)
        check(pg.locator('.rv-hist').count() == 1 and pg.locator('#rvObs').input_value() == '', 'resolve empties the field and keeps history')
        # empty text takes the card out of the pending list
        pg.fill('#rvObs', 'otra nota'); pg.click('[data-rvsave]'); pg.wait_for_timeout(500)
        def pend():
            pg.click('#reviewBtn'); pg.wait_for_timeout(300)
            if pg.locator('details[data-rvd="obs"][open]').count() == 0: pg.click('details[data-rvd="obs"] > summary'); pg.wait_for_timeout(150)
            return pg.locator('details[data-rvd="obs"] .rv-dn').inner_text().strip()
        n1 = pend()
        pg.click('details[data-rvd="obs"] .rv-row[data-go="frankfurt-kitchen"]'); pg.wait_for_timeout(300)
        pg.fill('#rvObs', ''); pg.click('[data-rvsave]'); pg.wait_for_timeout(500)
        n2 = pend()
        check(n1 == '1' and n2 == '0', f'clearing the text removes the card from the pending list ({n1} -> {n2})')
        pg.reload(); pg.wait_for_timeout(900); pg.click('#reviewBtn'); pg.wait_for_timeout(300)
        pg.click('details[data-rvd="obs"] > summary'); pg.wait_for_timeout(150)
        check(pg.locator('#panel .rv-total').count() >= 1 and pg.locator('details[data-rvd="obs"] [data-edlogin]').count() == 0, 'session keeps the password after reload')
        # summary without the password: public figures, notes behind a button
        ctx2 = b.new_context(viewport={'width': 1440, 'height': 900}); p2 = ctx2.new_page()
        p2.add_init_script("try{localStorage.setItem('lhd-lang','es')}catch(e){}")
        p2.route('**/en.wikipedia.org/**', lambda r: r.fulfill(status=200, content_type='application/json', body='{"query":{"pages":{}}}'))
        p2.goto('http://127.0.0.1:8765/index.html?editar'); p2.wait_for_timeout(800); p2.click('#reviewBtn'); p2.wait_for_timeout(300)
        check(p2.locator('.rv-total').count() >= 1 and p2.locator('#edPass').count() == 0, 'summary opens without a password and shows the figures')
        p2.click('details[data-rvd="obs"] > summary'); p2.wait_for_timeout(150)
        check(p2.locator('details[data-rvd="obs"] [data-edlogin]').count() == 1, 'notes list shows a button to enter the password')
        ctx2.close()
        pg.goto('http://127.0.0.1:8765/index.html#frankfurt-kitchen'); pg.wait_for_timeout(800)
        check('Test.jpg' in (pg.locator('.p-img img').get_attribute('src') or '') and pg.locator('.review').count() == 0 and pg.locator('.p-edit').count() == 0, 'public: image override visible, no notes nor pencil')
        check(pg.locator('#panel details.sources').count() == 1, 'public: Fuentes section present')
        r = pg.request.get('http://127.0.0.1:8765/editar.php'); check(r.status == 405, 'GET editar.php refused')
        r = pg.request.post('http://127.0.0.1:8765/editar.php', data=json.dumps({'clave': CL, 'accion': 'imagen', 'id': '../x', 'url': 'https://a'})); check(r.status == 400, 'bad id refused')
        r = pg.request.post('http://127.0.0.1:8765/editar.php', data=json.dumps({'clave': CL, 'accion': 'imagen', 'id': 'bauhaus', 'url': 'javascript:alert(1)'})); check(r.status == 400, 'bad url refused')
        r = pg.request.post('http://127.0.0.1:8765/editar.php', data=json.dumps({'clave': 'lhd2026', 'accion': 'leer'})); check(r.status == 403, 'old password refused')
        check(not errs, 'no page errors ' + ' | '.join(errs[:3]))
        b.close()
finally:
    srv.terminate()
# leave ediciones/ clean (the published site must ship with an empty imagenes.json and no review data)
open(ROOT + '/ediciones/imagenes.json', 'w').write('{}\n')
for f in ('revision.json', 'revision.lock', '.lock'):
    if os.path.exists(ROOT + '/ediciones/' + f): os.remove(ROOT + '/ediciones/' + f)
for f in os.listdir(ROOT + '/ediciones/copias'):
    if f.endswith('.json'): os.remove(ROOT + '/ediciones/copias/' + f)
print('ediciones/ cleaned')
print('RESULT:', 'PASS' if ok else 'FAIL')
